# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aanjhan Ranganathan
tagline:          'Researcher'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          http://aanjhan.github.io/hyde/

author:
  name:           'Aanjhan Ranganathan'
  url:            https://twitter.com/tuxmaniac

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aanjhan
